### PR TITLE
Develop #11 read in permit data

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo please review

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. I'll review.

**Comment by rpitingolo** [comment]
@maggiesu0725 do you have the CSV file open? Please close if you do.

**Comment by rpitingolo** [comment]
@ptatian is your intention that this should be broken up so that each year is its own dataset? Or that it should be added to the warehouse pretty much as-is?

**Comment by ptatian** [comment]
@rpitingolo It would seem to make sense to make it into one data set that we can add to every year. But I don't have a strong feeling about that.

**Comment by rpitingolo** [comment]
@ptatian thanks. I think adding to it year year makes sense. I'll leave the format as-is.

**Comment by rpitingolo** [comment]
@maggiesu0725 is the region defined differently for  this study? If not, please double check the county list to make sure they are all there.

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 We want to create a file that's a general resource for GreaterDC, so we are selecting for records in the MSA. 

When these data are used in the Regional Housing Framework analysis, they will have to be further subset into the study region, which is smaller than the MSA.

**Review by rpitingolo — APPROVED** [review]

**Comment by rpitingolo** [comment]
@maggiesu0725 please merge, sync and batch submit and then close this issue. Thanks!

**Pull request merged**
